name: Sync Dify Images
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Images
        run: |
          docker pull langgenius/dify-api:1.12.0
          docker pull langgenius/dify-web:1.12.0
          
      - name: Save to Tar
        run: |
          docker save langgenius/dify-api:1.12.0 langgenius/dify-web:1.12.0 -o dify_bundle.tar
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dify-images-tar
          path: dify_bundle.tar
