name: Sync Dify Images
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save
        run: |
          # 使用 latest 确保一定能拉取到镜像
          docker pull langgenius/dify-api:latest
          docker pull langgenius/dify-web:latest
          
          # 打包
          docker save langgenius/dify-api:latest langgenius/dify-web:latest -o dify_bundle.tar
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dify-images-package
          path: dify_bundle.tar
